### ISSUE TITLE
Change columns count mode

### ISSUE THREAD

**Issue by klawdyo** [DerYeger/vue2-masonry-wall#2]
Hi.
I would like suggest you changing scrollWidth by offsetWidth on columnsCount formula.

In my tests, both them has different values, as seen below:

![image](https://user-images.githubusercontent.com/100168/130089854-759d5814-bff2-449b-b887-1e41c3a499d9.png)

This difference causes: 

![image](https://user-images.githubusercontent.com/100168/130090441-228929a7-cfa9-42d9-9f76-cfa77fa38b92.png)

As you can see, parent's paddings is apparently not being considered.

Would you could test this?

**Comment by DerYeger** [comment]
> I would like suggest you changing scrollWidth by offsetWidth on columnsCount formula.

This is by design. Using `scrollWidth` enables horizontally-scrollable layouts.

> As you can see, parent's paddings is apparently not being considered.

I'd have to know your specific use case for a definite solution, but my recommendation is to put the `masonry-wall` component in a container that sets the desired width of the layout to ensure `scrollWidth` and `offsetWidth` are equal.

Alternatively, check out the [example page](https://vue2-masonry-wall.yeger.eu/). As you can see in the [source code](https://github.com/DerYeger/vue2-masonry-wall/blob/master/demo/serve.vue), the container actually has a padding of `1rem` but the content isn't overflowing like in your example.

I can also imagine that one of your items has a `width`/`min-width` larger than the specified `column-width`, which could cause the overflow.

**Comment by DerYeger** [comment]
Since v1.1.4 this library uses `getBoundingClientRect` instead of the height properties.
Could you test if this fixes your issue?

**Comment by klawdyo** [comment]
Yes. Tested. Problem solved.
But in the meantime, as my project uses Vuetify, I ended up creating my own component using its column scheme.

Thanks.

**Comment by DerYeger** [comment]
Thank you for testing it!

Personally, I'm using this component alongside Vuetify.
While Vuetify's grid system is suitable for many layouts, it does not support grids where rows don't have variable height per column.

**Comment by dosstx** [comment]
Would there be any issue with using this in a Bootstrap container with row and columns?

**Comment by DerYeger** [comment]
> Would there be any issue with using this in a Bootstrap container with row and columns?

I can't think of any issues, since the `masonry-wall` component uses a `ResizeObserver` for responsive sizing.
